### ISSUE TITLE
None of these issues have been fixed?

### ISSUE THREAD

**Issue by jandru** [MycroftAI/skill-alarm#21]
Looks like nobody is owning these issues. I am not a programmer but I wish I was. It would have been working six months ago. Too much wasted time. Not to mention the embarrasment when the skills failed while I was vetting MyCroft to my wife! She actually laughed out loud- not impressed.

**Comment by penrods** [comment]
FYI, I'm closing this issue because it adds absolutely nothing to the world.  You have joined github, cloned a couple repos and complained.  I can take criticism from those who are attempting to assist in any way.  But this "issue" is simply public complaining about something you have paid nothing for, in either dollars or effort.

I am not blocking you and you are welcome to participate in the project at any time.  But this is not participation.

**Comment by KathyReid** [comment]
@jandru please refer to our [code of conduct](https://github.com/MycroftAI/mycroft-skills/blob/18.02/CODE_OF_CONDUCT.md). Your interactions here are neither polite nor helpful. 

If you'd like to assist, feel free to do so, but please do so in a way that is respectful and helpful. 

Regards, 

Kathy Reid
Community Manager, Mycroft AI
